version: "3.8"
services:
  FeedbackPrize:
    image: nvidia/cuda:11.2.1-base
    container_name: FeedbackPrize
    user: root
    privileged: true
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "443:8888"
    volumes:
      - ../:/home/jovyan/
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             capabilities: [gpu]
             count: all
    stdin_open: true
    command: jupyter notebook --port 8888 --NotebookApp.token='' --ip=0.0.0.0 --allow-root
